### ISSUE TITLE
Make it possible to replace libraries

### ISSUE THREAD

**Issue by Sebobo** [mocdk/MOC.ImageOptimizer#15]
`jpegtran` and `optipng` and good libraries but on average are not reducing image sizes as much as possible.

I switched in my fork of the package to `jpegoptim` and `pngquant` which gave much better results in terms of resulting image sizes without losing much quality.

As this might be the decision of the user we should find a way to make this configurable.
The differences between the libraries are not that huge so maybe we could move this configuration to yaml or provide a way to override which library is used.

**Comment by aertmann** [comment]
Yep thought of that initially, but didn't implement it.

Would suggest to add something like this to the configuration:
```
library: 'jpegtran'
arguments: "${'-copy none -optimize ' + (progressive ? '-progressive ' : '') + '-outfile ' + file ' + ' ' + file}"
arguments: "${'-o' + optimizationLevel + ' -strip all -out ' + file ' + ' ' + file}"'`
```

Using Eel to convert the arguments string.

Feel free to submit a PR making it possible.

Also both are also available as npm packages..
https://www.npmjs.com/package/pngquant-bin
https://www.npmjs.com/package/jpegoptim-bin
