### ISSUE TITLE
Allow asynchronous optimisation

### ISSUE THREAD

**Issue by mficzel** [mocdk/MOC.ImageOptimizer#19]
Currently the images are optimized on the fly ... that causes some delay if large sites are rendered with many images at once. 

I think adding an option to defer the optimization would be quite easy with the Flowpack.JobQueue.Common package that could control the actual optimization process. Ofcourse this should be optional since the JobQueue needs some setup effort.

Would you like a pr for such a feature or shall i create a custom package.

**Comment by aertmann** [comment]
Hey yeah have thought about such a feature too, would be very cool to add.

Package or PR? Really depends tbh. If there's a way to do it without a hard dependency on the JobQueue stuff, then by all means. But most likely a suggested package is a better approach.

One issue I've seen with the JobQueue packages is that it's difficult to provide one package that works out of the box with all of the different adapters (Redis, Doctrine, Beanstalk) as the configuration and dependencies are conflicting and there's no package interface (composer provide) used for them. Would be really cool to work on that to simplify using those packages.

Btw. in case you have pretty standard sizes for your images, using thumbnail presets and auto-generation can help this issue as well. But I agree that using an async option for the optimization would be a nice additional as well.

**Comment by mficzel** [comment]
Thank you for the feedback, i think i will end up creating a fork. To make this a real soft dependency would mean extracting the executor into a separate package that allows different implementations. In the end it is better to have two completely separate packages then 3 interdepending ones.
