### ISSUE TITLE
JPEG quality seems to degrade when redeploying or clearing the cached images

### ISSUE THREAD

**Issue by Sebobo** [mocdk/MOC.ImageOptimizer#2]
After uploading a new image it looks fine. After redeploying a few times or clearing caches the image gets worse and worse.

**Comment by dfeyer** [comment]
Yes, everytime the Resource management publish a resource it's processed by MOC.ImageOptimizer ... let's see if we can add a processing cache, basically a single SHA must be processed only once, so we can use the new persistent cache in Flow 3.0

**Comment by dfeyer** [comment]
An other issue (or risk) is that the current version optimize any image (not only Variant or Thumbnail), so the risk to optimize the original file more than once is important. The other problem I see is that this process is done during the shutdown, so if something break ... it's hard to get the exception correctly. Let's see if we can improve that too.

**Comment by dfeyer** [comment]
@Sebobo Can you test https://github.com/mocdk/MOC.ImageOptimizer/pull/7 ?

/me I think I mess a little bit my PR ... don't really now how to handle dependencies between PR, look like the PR7 contains all the other :(

**Comment by Sebobo** [comment]
Wow that's great!
Not sure if I'm able to look at it today but I will test it.

What happens if I want to rerender all images? 
Flush the persistent cache?

I think when the plugin is not set up correctly it currently fails silently and when the result is still cached as `done` we have a problem there.

**Comment by hlubek** [comment]
Hi there,

I think modifying the original resource is a risk. We should find a way to have an optimized resource variant on top of the original that is shared between deployments. Maybe Robert can help to find a solution especially with the new tools in Flow 3.0. I suspect an adapter for publishing targets that persistently stores the optimized versions and links them instead of the original file could be a proper solution.

**Comment by dfeyer** [comment]
I agree that the risk to touch the original file is a really bad thing.

**Comment by aertmann** [comment]
All mentioned issues solved with 198678b25f20733fd76bd5b56fc1928c34090e82

@dfeyer: Not sure what you mean with during shutdown, nothing happens during shutdown..
