### ISSUE TITLE
jpegtran and optipng binaries have different names than their folder

### ISSUE THREAD

**Issue by Sebobo** [mocdk/MOC.ImageOptimizer#3]
In the aspect the code expects both to be the same.

Foldername is "jpegtran-bin", binary is "jpegtran"
Foldername is "optipng-bin", binary is "optipng"

**Comment by dfeyer** [comment]
Solve in the PR https://github.com/mocdk/MOC.ImageOptimizer/pull/6

**Comment by aertmann** [comment]
Fixed with efba5c88499fc724b1454c825a68cd0e44dd2c8d
