### ISSUE TITLE
Breaks Entity Manager in Flow 3

### ISSUE THREAD

**Issue by Sebobo** [mocdk/MOC.ImageOptimizer#4]
In the function `optimizePublishedFile`of the `ResourcePublisherAspect` class in Flow 2 the absolute path was returned and in Flow 3 only the relative path to the resource.
This breaks the `optimizeFile` function and leads to an Exception of the Entity Manager when doctrine tries to store a resource.
For some reason the aspect doesn't appear in the Stacktrace.

Fixed it locally by injecting `resource.targets.localWebDirectoryPersistentResourcesTarget.targetOptions.path` from `TYPO3.Flow` and using it as prefix to get the absolute path.
Not sure if that is the perfect way.

**Comment by dfeyer** [comment]
This PR fix the issue: https://github.com/mocdk/MOC.ImageOptimizer/pull/5

I think injecting the value is not correct, because we can have multiple target with different publishing path.

**Comment by aertmann** [comment]
PR merged thanks to @dfeyer
