### ISSUE TITLE
Do not install npm packages on each deployment

### ISSUE THREAD

**Issue by mrimann** [mocdk/MOC.ImageOptimizer#8]
While building a demo site with Neos, I included your ImageOptimizer and it works very fine. But while deploying the whole installation via Surf, I see that the npm packages are installed every time.

Could the npm packages be put to a place that is shared across deployments?

Or can you explain in the Readme, how the option `useGlobalBinary` can be used (e.g. how to install the packages globally)?

**Comment by reflexxion** [comment]
`npm install -g gifsicle jpegtran-bin optipng-bin svgo`

**Comment by mrimann** [comment]
I tried that and failed to get it working:

Installing the npm packages globally worked fine, they are available under `/usr/local/bin/` and I see that they get called with status "OK" (according to the Neos log). But the resulting images are the "originals" not optimized ones.

I changed the config of the MOC.ImageOptimizer Package to use the global npm packages and provided the proper path to the executables. I also made sure the OpenBasedir-Restriction allows access to this directory.

Any hint what could have gone wrong?

**Comment by aertmann** [comment]
@mrimann: Hard to tell without more information, I've always used the global packages and haven't had any issues. One thing I've noticed is that it can sometimes be a bit tricky to know if a file was actually optimized and that browser caching and cache proxies can play tricks on you.

**Comment by kdambekalns** [comment]
I just created #9 - basically automatic installation should never happen, @mrimann!?

**Comment by aertmann** [comment]
Solved with #9
